### PR TITLE
#14 : Set up a P reference tracking test and adapt the parameters so …

### PR DESCRIPTION
**Pull request by adriguir**
…that the behavior for WECC and IEC is identical

Modifications done compared to the original test case:

1. Replace the infinite bus models in order not to have any modification
2. Include a variation of 0.2 pu on PRef at t = 5 s
3. Modify settings in the IEC and WECC models

Regarding the settings modifications:

1. In IEC, modifying tPWTRef4A to 0.001 s instead of 0.01 s to make the response identical to the slewRateLimiter in the WECC model.
2. In IEC, modify the value of DPMaxP4APu to 999, equal to the same value DPMax0 in WECC.

With these values, the behaviors of the two models are exactly the same.
Structurally for this kind of test, there is no source of differences for reference tracking and this is proved in simulation.

StepP_ipCmd
StepP_P

### CODE REVIEW

**Comment by martinscripts** [comment]
Hey Adrien,
you did the implementation with the old REGC version, not with the REGC_A, correct?
Maybe rebase your branch to commit dc54418 or so?

I think we should firstly pull all the new parameters from REGC_A up to the WECC_WT4B model level, so we can adjust them differently in every test case.

Greetings!
.Martin

Von: Adrien Guironnet ***@***.***>
Gesendet: Dienstag, 1. August 2023 16:10
An: bertrtam00/wecc_iec_model_comparison ***@***.***>
Cc: Franke, Martin ***@***.***>; Review requested ***@***.***>
Betreff: Re: [bertrtam00/wecc_iec_model_comparison] #14 : Set up a P reference tracking test and adapt the parameters so … (PR #17)


@adriguir<https://github.com/adriguir> requested your review on: #17<https://github.com/bertrtam00/wecc_iec_model_comparison/pull/17> #14<https://github.com/bertrtam00/wecc_iec_model_comparison/issues/14> : Set up a P reference tracking test and adapt the parameters so ….

**Comment by adriguir** [comment]
Yes, I can rebase on the new main and use the newer version of REGC_A without too much problem.
For small modifications, as I did, it shouldn't have any impact

**Comment by martinscripts** [comment]
Thanks.

Yes, unfortunately until now it still does because the parameter dependencies aren’t sorted out yet. (hence it doesn’t initialize correctly, for example)
I haven’t quite figured it out yet, struggling to get it to initialize correctly. For some reason Id0Pu is =0 inside regc_a but I set it to 0.5 in the parent models.

Von: Adrien Guironnet ***@***.***>
Gesendet: Dienstag, 1. August 2023 16:31
An: bertrtam00/wecc_iec_model_comparison ***@***.***>
Cc: Franke, Martin ***@***.***>; Review requested ***@***.***>
Betreff: Re: [bertrtam00/wecc_iec_model_comparison] #14 : Set up a P reference tracking test and adapt the parameters so … (PR #17)


Yes, I can rebase on the new main and use the newer version of REGC_A without too much problem.
For small modifications, as I did, it shouldn't have any impact

**Comment by adriguir** [comment]
Already fine for having the parameters available at the upper level.
I'm having a look for the init part. Keep you posted

**Comment by martinscripts** [comment]
thank you.

here is a plot of active power. Input is a step from 0.005 to 0.01, as can be seen in the IEC response.
(input in unit base is a step from .5 to 1)

image

**Comment by adriguir** [comment]
It's because you had forced Rrpwr to be equal to 20 in your implementation. I will correct that.

**Pull request merged**
